### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJavaString#1]
Running

```
./gradlew
```

gives 

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by davidmoten** [comment]
This is not enough  for the project to build. There are compile errors due to AssertObservable not being present. I've raised an issue on RxJava to see if it should hold that class for use by RxJavaString.

**Comment by benjchristensen** [comment]
Fixed and released.
