### ISSUE TITLE
Release please and tag cleanup

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJavaString#18]
Can we get a new release to Maven Central please.

We need to clean up the release tags as well. When we click on https://github.com/ReactiveX/RxJavaString/releases in github it indicates that the latest release is 0.21.0 when the latest release to Maven Central was 0.22.0. 1.0.0 is in the list of releases but is not in Maven Central.

**Comment by akarnokd** [comment]
Trying to sort this out through #19.
