### ISSUE TITLE
Release v0.23

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJavaString#19]
@davidmoten can we release a new version of RxJavaString?

Just run into a [StackOverflow](http://stackoverflow.com/questions/30308557/stringobservable-frominputstream-share-cause-immediate-missingbackpressure) issue due to lack of backpressure support.

/cc @benjchristensen

**Comment by davidmoten** [comment]
Yep I believe so. I requested this a little while ago #18. A bit of cleanup is needed on the release tags as well.

**Comment by davidmoten** [comment]
@benjchristensen @abersnaze can we get a release on this please, and a cleanup of the tags?

**Comment by benjchristensen** [comment]
Should we release 0.23, or do you want to do 1.0?

**Comment by Crystark** [comment]
+1 at releasing something. It's kinda confusing between the tag (1.0) the github releases (0.21) and maven (0.22)

**Comment by abersnaze** [comment]
Sorted out all of the travis build stuff and publish 1.0.1 to bintray and sonatype.

**Comment by abersnaze** [comment]
unless there are additional problems I'm closing the issue
