### ISSUE TITLE
maven central release?

### ISSUE THREAD

**Issue by fommil** [ReactiveX/RxJavaString#3]
It doesn't look like you're published yet

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.reactivex%22

**Comment by zsxwing** [comment]
ping @benjchristensen

**Comment by quidryan** [comment]
Looks like it wasn't linked to JCenter. I just submitted a request for it.

**Comment by benjchristensen** [comment]
Yeah I forgot to do that for this project.

**Comment by benjchristensen** [comment]
Just synced to Maven Central. Will take some time for it to show up in their indexes.
