### ISSUE TITLE
Incompatibility with rxjava 1.1.0

### ISSUE THREAD

**Issue by sarthakn7** [ReactiveX/RxJavaString#33]
As AsyncOnSubscribe has been removed from rx-java version 1.1.0 we are getting ClassNotFound exception when running with that version. The usage needs to be replaced with SyncOnSubscribe.

**Comment by akarnokd** [comment]
Yes, the companion libraries haven't been updated. 1.1.0 has mainly API surface changes but no other funcional changes compared to 1.0.17 so if you can, go back to 1.0.17 for the time being.
