### ISSUE TITLE
The byLine operator is platform dependent and therefore a bit unreliable

### ISSUE THREAD

**Issue by flyaruu** [ReactiveX/RxJavaString#35]
I'm parsing a CSV file, and the byLine considers the whole file one long line.
The problem seems to be that the file lines use only CR line ends. (I don't know where that file came from)

The code looks like this:
    public static Observable<String> byLine(Observable<String> source) {
        return split(source, System.getProperty("line.separator"));
    }

Using the system property for line separator isn't a very good idea, I think. It works when the file originates from the same platform, but it is a bit of a bugger to debug, and it can cause a 'works on my system' scenario.

I'd say just use the split and get rid of the byLine? Or add an explicit separator parameter (but then it is identical to split)

regards, Frank

**Comment by Crystark** [comment]
Indeed, see https://github.com/ReactiveX/RxJavaString/pull/31 (which references https://github.com/ReactiveX/RxJavaString/pull/30)

I'm having some problems with the solution I used then because of https://github.com/ReactiveX/RxJavaString/issues/33.

**Comment by abersnaze** [comment]
@flyaruu and @Crystark can this issue be closed?

**Comment by Crystark** [comment]
Looks like it can to me but i'll let @flyaruu confirm

**Comment by abersnaze** [comment]
Closing for now reopen if problem continues.
