### ISSUE TITLE
Preview 1.1.0

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJavaString#38]
I'm ready to cut a 1.1.0 release of the library. If I don't at least two :+1: or an objection in a week I'll push it. If I do a few :+1: then I'll push it immediately.

> - [Pull 31](https://github.com/ReactiveX/RxJavaString/pull/31) Make byLine handle carriage newline and just newline equally.
> - [Pull 36](https://github.com/ReactiveX/RxJavaString/pull/36) update rx dependency to 1.1.1 
> - [Pull 28](https://github.com/ReactiveX/RxJavaString/pull/28) use the experimental version of `using()` that closes resources eagerly.
> 
> Artifacts: [Maven Central](http://search.maven.org/#artifactdetails%7Cio.reactivex%7Crxjava-string%7C1.1.0%7C)

**Comment by robholmes** [comment]
:+1:

**Comment by davidmoten** [comment]
:+1:

**Comment by abersnaze** [comment]
done

**Comment by robholmes** [comment]
Thank you @abersnaze!
